#pragma once

#include <stdbool.h>
#include <stdint.h>

/** On-device WiFi app store: fetches the flat catalog published by CI and
 *  downloads .fap files straight to /ext/apps/<category>/.
 *
 *  Same shape as wlan_sd_update: the work runs in a dedicated xTaskCreate task
 *  (NOT a FuriThread — esp_http_client drives lwIP sockets, which must not be
 *  driven from a FuriThread), and progress is published through volatile fields
 *  that the scene polls in its tick handler.
 *
 *  The catalog is the flat `catalog.txt` generated by tools/make_catalog.py
 *  beside catalog.json, so the firmware needs no JSON parser. */

typedef enum {
    WlanAppStoreIdle = 0,
    WlanAppStoreFetching,   /* downloading the catalog */
    WlanAppStoreReady,      /* catalog parsed, entries readable */
    WlanAppStoreInstalling, /* downloading one .fap */
    WlanAppStoreDone,       /* install finished */
    WlanAppStoreError,
} WlanAppStorePhase;

typedef struct WlanAppStore WlanAppStore;

WlanAppStore* wlan_app_store_alloc(void);
void wlan_app_store_free(WlanAppStore* s);

/** Start fetching the catalog. No effect while the worker is busy. */
void wlan_app_store_fetch(WlanAppStore* s);

/** Start installing entry `index`. Only valid in the Ready phase. */
void wlan_app_store_install(WlanAppStore* s, uint32_t index);

/** Request cancel and block (up to ~5 s) until the worker has stopped. */
void wlan_app_store_cancel(WlanAppStore* s);

WlanAppStorePhase wlan_app_store_get_phase(const WlanAppStore* s);
uint8_t wlan_app_store_get_percent(const WlanAppStore* s);
uint32_t wlan_app_store_get_speed_kbps(const WlanAppStore* s);
const char* wlan_app_store_get_error(const WlanAppStore* s);
bool wlan_app_store_is_running(const WlanAppStore* s);

/** Catalog accessors. Only safe once the phase is Ready or later — while the
 *  worker is Fetching it is rewriting the very buffer these point into. */
uint32_t wlan_app_store_count(const WlanAppStore* s);
const char* wlan_app_store_name(const WlanAppStore* s, uint32_t i);
const char* wlan_app_store_category(const WlanAppStore* s, uint32_t i);
uint32_t wlan_app_store_size(const WlanAppStore* s, uint32_t i);

/** Where the most recent install landed, for the success message. */
const char* wlan_app_store_get_dest(const WlanAppStore* s);
